#!/usr/bin/env bun
/**
 * Generates TypeScript types from an OpenAPI spec for the RPI Integration API.
 *
 * Reads RPI_OPENAPI_SPEC from the environment (URL or file path).
 * Errors if unset and no generated file already exists.
 * Pass --check to verify the existing generated file is up-to-date.
 */
import { existsSync, readFileSync } from "node:fs";
import { resolve, dirname, basename } from "node:path";
import { fileURLToPath } from "node:url";
import { sanitizeGeneratedTypes } from "./sanitize-generated.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const outputPath = resolve(__dirname, "../src/client/rpi-api.generated.ts");

// Load the root .env — the single source of truth. Bun only auto-loads .env from
// the cwd, which is packages/mcp-rpi when this runs via the workspace filter, so
// root vars (RPI_INTEGRATION_API_URL, RPI_OPENAPI_SPEC) would otherwise be unseen.
// Same manual-parse pattern as apps/server/src/index.ts; existing env wins.
const rootEnv = resolve(__dirname, "../../../.env");
if (existsSync(rootEnv)) {
  for (const line of readFileSync(rootEnv, "utf8").split("\n")) {
    const t = line.trim();
    if (!t || t.startsWith("#")) continue;
    const eq = t.indexOf("=");
    if (eq < 1) continue;
    const k = t.slice(0, eq).trim();
    let v = t.slice(eq + 1).trim();
    if (!v.startsWith('"') && !v.startsWith("'")) {
      const c = v.indexOf("#");
      if (c > 0) v = v.slice(0, c).trim();
    }
    if (!(k in process.env)) process.env[k] = v;
  }
}
// Spec source (dev-only; reads the real env): an explicit RPI_OPENAPI_SPEC (URL or
// local file path) wins; otherwise derive from the configured instance's swagger
// endpoint. The existing warn-and-skip guard stays when neither is set.
const explicitSpec = process.env.RPI_OPENAPI_SPEC?.trim();
const baseUrl = process.env.RPI_INTEGRATION_API_URL?.trim().replace(/\/+$/, "");
const specSource =
  explicitSpec || (baseUrl ? `${baseUrl}/swagger/v1/swagger.json` : undefined);
const isCheck = process.argv.includes("--check");

if (!specSource) {
  if (existsSync(outputPath)) {
    console.warn(
      "WARNING: neither RPI_OPENAPI_SPEC nor RPI_INTEGRATION_API_URL is set. " +
        "Skipping type generation — using existing generated file.",
    );
    process.exit(0);
  }
  console.error(
    "ERROR: no OpenAPI spec source and no generated types file exists.\n" +
      "Set RPI_OPENAPI_SPEC to a URL or local file path, OR set RPI_INTEGRATION_API_URL\n" +
      "(derives {base}/swagger/v1/swagger.json), then re-run.\n" +
      "Example: RPI_OPENAPI_SPEC=/path/to/openapi.yaml",
  );
  process.exit(1);
}

// Validate that file-path sources actually exist
const isUrl = specSource.startsWith("http://") || specSource.startsWith("https://");
if (!isUrl && !existsSync(specSource)) {
  console.error(`ERROR: OpenAPI spec file not found: ${specSource}`);
  process.exit(1);
}

const targetPath = isCheck ? `${outputPath}.check` : outputPath;

// The generated file is COMMITTED to the public repo. Never record a live instance
// URL as its source — that would leak the customer's host (identifier-leak gate).
// Use a neutral label for URL sources; for local file paths use the basename only,
// so a dev's absolute machine path (e.g. a scratchpad dir) never lands in the header.
const sourceLabel = isUrl
  ? "RPI Integration API OpenAPI spec (derived from the configured instance)"
  : basename(specSource);

console.log(`Generating types from: ${sourceLabel}`);
console.log(`Output: ${targetPath}`);

const proc = Bun.spawn(
  ["bunx", "openapi-typescript", specSource, "-o", targetPath],
  { stdout: "inherit", stderr: "inherit" },
);
const exitCode = await proc.exited;

if (exitCode !== 0) {
  console.error(`openapi-typescript exited with code ${exitCode}`);
  process.exit(exitCode);
}

// Sanitize before committing: rewrite corporate example addresses from the spec's
// JSDoc to example.com so no real address ships in the public-repo types.
const generated = sanitizeGeneratedTypes(await Bun.file(targetPath).text());
// Header stays free of volatile values (no absolute path, no timestamp) so the
// committed file doesn't churn on every regen. The --check body-compare below
// strips exactly these 5 leading lines (4 comments + blank), so keep that shape.
const header =
  `// @ts-nocheck — generated vendored types; not hand-maintained, skip type-checking\n` +
  `// Auto-generated by openapi-typescript — DO NOT EDIT\n` +
  `// Source: ${sourceLabel}\n` +
  `// Regenerate with: bun run generate:types:rpi\n\n`;
await Bun.write(targetPath, header + generated);

if (isCheck) {
  // Compare with the committed file
  if (!existsSync(outputPath)) {
    console.error("ERROR: No existing generated file to check against.");
    await Bun.write(targetPath, ""); // cleanup
    process.exit(1);
  }
  const existing = await Bun.file(outputPath).text();
  // The committed file is [5-line header] + body; `generated` is the fresh body
  // (sanitized, no header yet). Strip only the committed file's header, then
  // compare bodies. (Previously also stripped `generated` — an off-by-5 bug that
  // made the check always fail once a spec source actually resolves.)
  const stripHeader = (s: string) => s.split("\n").slice(5).join("\n");
  if (stripHeader(existing) !== generated) {
    console.error(
      "ERROR: Generated types are out of date. Run 'bun run generate:types' to update.",
    );
    await Bun.file(targetPath).delete();
    process.exit(1);
  }
  console.log("Generated types are up to date.");
  await Bun.file(targetPath).delete();
}

console.log("Done.");