#!/usr/bin/env bun
/**
 * Generates TypeScript types from an OpenAPI spec for the DRH (Data Readiness
 * Hub) OP-ServicesAPI.
 *
 * Reads DRH_OPENAPI_SPEC from the environment (URL or file path).
 * Errors if unset and no generated file already exists.
 * Pass --check to verify the existing generated file is up-to-date.
 *
 * Mirrors packages/mcp-rpi/scripts/generate-types.ts (intentional copy — the
 * two MCP servers stay independent; mcp-rpi is not refactored into a shared lib).
 */
import { existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const outputPath = resolve(__dirname, "../src/client/drh-api.generated.ts");
const specSource = process.env.DRH_OPENAPI_SPEC;
const isCheck = process.argv.includes("--check");

if (!specSource) {
  if (existsSync(outputPath)) {
    console.warn(
      "WARNING: DRH_OPENAPI_SPEC is not set. Skipping type generation — using existing generated file.",
    );
    process.exit(0);
  }
  console.error(
    "ERROR: DRH_OPENAPI_SPEC is not set and no generated types file exists.\n" +
      "Set DRH_OPENAPI_SPEC in your .env to a URL or local file path for the OpenAPI spec.\n" +
      "Example: DRH_OPENAPI_SPEC=https://<your-drh-instance>/api-op/openapi.json\n" +
      "Example: DRH_OPENAPI_SPEC=/path/to/openapi.json",
  );
  process.exit(1);
}

// Validate that file-path sources actually exist
const isUrl = specSource.startsWith("http://") || specSource.startsWith("https://");
if (!isUrl && !existsSync(specSource)) {
  console.error(`ERROR: OpenAPI spec file not found: ${specSource}`);
  process.exit(1);
}

const targetPath = isCheck ? `${outputPath}.check` : outputPath;

console.log(`Generating types from: ${specSource}`);
console.log(`Output: ${targetPath}`);

const proc = Bun.spawn(
  ["bunx", "openapi-typescript", specSource, "-o", targetPath],
  { stdout: "inherit", stderr: "inherit" },
);
const exitCode = await proc.exited;

if (exitCode !== 0) {
  console.error(`openapi-typescript exited with code ${exitCode}`);
  process.exit(exitCode);
}

// Prepend a header comment. NOTE: the source is deliberately a GENERIC label,
// not the raw `specSource` — this file is committed to the (public) OSS repo, so
// we must not bake in an internal DRH instance hostname or a local dev path.
// Regenerate by setting DRH_OPENAPI_SPEC. (The `--check` compare strips the
// first 5 header lines, so this label never affects the up-to-date check.)
const generated = await Bun.file(targetPath).text();
const header =
  `// @ts-nocheck — generated vendored types; not hand-maintained, skip type-checking\n` +
  `// Auto-generated by openapi-typescript — DO NOT EDIT\n` +
  `// Source: DRH OP-ServicesAPI OpenAPI spec (set DRH_OPENAPI_SPEC to regenerate)\n` +
  `// Generated: ${new Date().toISOString()}\n\n`;
await Bun.write(targetPath, header + generated);

if (isCheck) {
  // Compare with the committed file
  if (!existsSync(outputPath)) {
    console.error("ERROR: No existing generated file to check against.");
    await Bun.write(targetPath, ""); // cleanup
    process.exit(1);
  }
  const existing = await Bun.file(outputPath).text();
  // Compare bodies. `generated` here is the RAW openapi-typescript output (read
  // above, before the header was prepended), so it is already header-less —
  // strip the 5-line header only from the committed `existing`. (The verbatim
  // RPI copy stripped BOTH, lopping 5 real type lines off `generated` so the
  // check could never pass; corrected here. mcp-rpi left as-is per zero-diff.)
  const stripHeader = (s: string) => s.split("\n").slice(5).join("\n");
  if (stripHeader(existing) !== generated) {
    console.error(
      "ERROR: Generated types are out of date. Run 'bun run generate:types' to update.",
    );
    await Bun.file(targetPath).delete();
    process.exit(1);
  }
  console.log("Generated types are up to date.");
  await Bun.file(targetPath).delete();
}

console.log("Done.");
