#!/usr/bin/env bun
/**
 * bun run licenses — generate THIRD-PARTY-LICENSES.md
 *
 * Walks the installed dependency tree and emits a deterministic manifest of
 * every third-party package (name @ version → SPDX license id), grouped by
 * license. The output (THIRD-PARTY-LICENSES.md at the repo root) is committed
 * so a fresh clone ships the inventory without a network round-trip; rerun
 * this after a dependency change and commit the diff.
 *
 * Source of truth is Bun's flat package store
 * (node_modules/.bun/node_modules) — that directory holds one real, deduped
 * copy of each resolved package@version, so we read each package.json's
 * `license` field directly rather than shelling out to an npm-only tool that
 * doesn't understand Bun's layout.
 *
 * Pass --check to verify the committed file is up to date without rewriting it
 * (exit 1 on drift) — useful in a pre-PR sweep.
 *
 * History: added for the OSS license inventory. NOTICE points here for the
 * full attribution list; this script keeps that list reproducible.
 */

import { readdirSync, readFileSync, existsSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, "..");
const STORE = join(REPO_ROOT, "node_modules", ".bun", "node_modules");
const OUT = join(REPO_ROOT, "THIRD-PARTY-LICENSES.md");

interface Pkg {
  name: string;
  version: string;
  license: string;
}

const seen = new Map<string, Pkg>();

function normalizeLicense(j: any): string {
  let lic = j.license ?? j.licenses ?? "UNKNOWN";
  if (typeof lic === "object") {
    lic = Array.isArray(lic)
      ? lic.map((x: any) => x.type || x).join(" OR ")
      : lic.type || "UNKNOWN";
  }
  return String(lic);
}

function readPkg(dir: string): void {
  const pj = join(dir, "package.json");
  if (!existsSync(pj)) return;
  try {
    const j = JSON.parse(readFileSync(pj, "utf8"));
    if (!j.name) return;
    seen.set(`${j.name}@${j.version}`, {
      name: j.name,
      version: j.version ?? "?",
      license: normalizeLicense(j),
    });
  } catch {
    // Unparseable package.json — skip; the install itself would have failed.
  }
}

function walk(base: string): void {
  let entries: string[] = [];
  try {
    entries = readdirSync(base);
  } catch {
    return;
  }
  for (const e of entries) {
    const p = join(base, e);
    if (e.startsWith("@")) {
      // scoped package dir — one level deeper
      for (const sub of readdirSync(p)) readPkg(join(p, sub));
    } else {
      readPkg(p);
    }
  }
}

if (!existsSync(STORE)) {
  console.error(
    `error: Bun package store not found at ${STORE} — run \`bun install\` first`,
  );
  process.exit(1);
}

walk(STORE);

const all = [...seen.values()].sort(
  (a, b) => a.name.localeCompare(b.name) || a.version.localeCompare(b.version),
);

// Group by license id for the distribution summary.
const byLicense = new Map<string, Pkg[]>();
for (const p of all) {
  const arr = byLicense.get(p.license) ?? [];
  arr.push(p);
  byLicense.set(p.license, arr);
}
const licensesSorted = [...byLicense.entries()].sort(
  (a, b) => b[1].length - a[1].length || a[0].localeCompare(b[0]),
);

// Build markdown. No timestamp — keep the file deterministic so the --check
// diff only moves when the dependency set actually changes.
const lines: string[] = [];
lines.push("# Third-Party Licenses");
lines.push("");
lines.push(
  "This file is generated by `bun run licenses` (see " +
    "`scripts/generate-third-party-licenses.ts`). It lists every third-party " +
    "package in the resolved dependency tree, grouped by SPDX license " +
    "identifier. Regenerate and commit after any dependency change.",
);
lines.push("");
lines.push(`Total unique packages: **${all.length}**`);
lines.push("");
lines.push("## License distribution");
lines.push("");
lines.push("| Count | License |");
lines.push("| ----: | ------- |");
for (const [lic, pkgs] of licensesSorted) {
  lines.push(`| ${pkgs.length} | ${lic} |`);
}
lines.push("");
lines.push("## Packages by license");
lines.push("");
for (const [lic, pkgs] of licensesSorted) {
  lines.push(`### ${lic}`);
  lines.push("");
  for (const p of pkgs) lines.push(`- ${p.name}@${p.version}`);
  lines.push("");
}

const content = lines.join("\n") + "\n";

if (process.argv.includes("--check")) {
  const current = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
  if (current === content) {
    console.log(`THIRD-PARTY-LICENSES.md is up to date (${all.length} packages)`);
    process.exit(0);
  }
  console.error(
    "THIRD-PARTY-LICENSES.md is out of date — run `bun run licenses` and commit the diff",
  );
  process.exit(1);
}

writeFileSync(OUT, content);
console.log(
  `wrote THIRD-PARTY-LICENSES.md — ${all.length} packages across ${byLicense.size} license ids`,
);
